name: centrifuge
version: 0.14.1

description: >
  Dart client to communicate with Centrifuge and Centrifugo from Flutter and VM
  over WebSockets

homepage: https://github.com/centrifugal/centrifuge-dart

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  fixnum: ^1.0.0
  meta: ^1.3.0
  protobuf: ">=2.0.0 <4.0.0"
  web_socket_channel: ^2.4.0

dev_dependencies:
  build_runner: ^2.0.3
  mockito: ^5.0.7
  test: ^1.17.4
