name: centrifuge
version: 0.9.1

description: >
  Dart client to communicate with Centrifuge and Centrifugo from Flutter and VM over dart:io WebSocket

homepage: http://github.com/centrifugal/centrifuge-dart

environment:
 sdk: '>=2.12.0 <3.0.0'

dependencies:
 meta: ^1.3.0
 protobuf: ^2.0.0
 fixnum: ^1.0.0

dev_dependencies:
  test: ^1.17.4
  mockito: ^5.0.7
  build_runner: ^2.0.3
